### ISSUE TITLE
 Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number.

### ISSUE THREAD

**Issue by araczkowski** [sviete/AIS-devices#1]
2019-06-21 12:33:00.217 16006-16025/pl.sviete.dom.devices E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
    Process: pl.sviete.dom.devices, PID: 16006
    java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
        at android.arch.persistence.room.RoomOpenHelper.checkIdentity(RoomOpenHelper.java:135)
        at android.arch.persistence.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:115)
        at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:151)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:409)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)
        at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:96)
        at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:54)
        at android.arch.persistence.room.RoomDatabase.query(RoomDatabase.java:233)
        at pl.sviete.dom.devices.db.AisDeviceDao_Impl$4.compute(AisDeviceDao_Impl.java:188)
        at pl.sviete.dom.devices.db.AisDeviceDao_Impl$4.compute(AisDeviceDao_Impl.java:174)
        at android.arch.lifecycle.ComputableLiveData$2.run(ComputableLiveData.java:100)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by l0kers** [comment]
Nie dodawałem skryptów do updatów bazy (apka jeszcze w wersji dev, więc szkoda mi było czasu). Usuń dane aplikacji, to wyczyści bazę danych i utworzy na nowo schematy.
